// Every public route is declared once. Change updated only for a real content update.
export const pages = [
  { id: 'home', path: '', label: 'Início', title: 'Nutricionista em Passos, MG | Fernanda Lemos', description: 'Fernanda Lemos, nutricionista em Passos, MG. CRN 9-30894. Conheça a proposta de acompanhamento e converse pelo WhatsApp sobre sua consulta.', updated: '2026-09-16' },
  { id: 'sobre', path: 'sobre/', label: 'Sobre a Fernanda', title: 'Sobre Fernanda Lemos | Nutricionista em Passos, MG', heading: 'Antes do prato,<br>vem <em>a sua história.</em>', eyebrow: 'Conheça a Fernanda', description: 'Conheça Fernanda Lemos, nutricionista em Passos, MG, CRN 9-30894, e sua proposta de cuidado com escuta, individualidade e respeito à rotina.', intro: 'Conheça a profissional e o olhar que orienta a proposta de cuidado.', updated: '2026-09-16', type: 'AboutPage' },
  { id: 'acompanhamento', path: 'acompanhamento/', label: 'Acompanhamento', title: 'Acompanhamento nutricional em Passos | Fernanda Lemos', heading: 'O cuidado se constrói<br><em>com você.</em>', eyebrow: 'Acompanhamento nutricional', description: 'Entenda a proposta de acompanhamento nutricional de Fernanda Lemos: escuta, construção do cuidado e ajustes que consideram sua rotina e preferências.', intro: 'Da primeira escuta aos ajustes do caminho, a sua vida faz parte da conversa.', updated: '2026-09-16' },
  { id: 'conteudos', path: 'conteudos/', label: 'Conteúdos', title: 'Conteúdos e primeira consulta | Fernanda Lemos', heading: 'Conhecer também<br>é uma forma de <em>cuidar.</em>', eyebrow: 'Leituras e orientações', description: 'Informações práticas para conhecer o acompanhamento de Fernanda Lemos, organizar a primeira consulta e encontrar respostas para suas dúvidas.', intro: 'Um espaço para encontrar informações antes de dar o próximo passo.', updated: '2026-09-16', type: 'CollectionPage' },
  { id: 'duvidas', path: 'duvidas/', label: 'Dúvidas frequentes', title: 'Dúvidas sobre a consulta nutricional | Fernanda Lemos', heading: 'Suas perguntas<br>têm <em>lugar aqui.</em>', eyebrow: 'Dúvidas frequentes', description: 'Tire dúvidas sobre a primeira consulta, preferências alimentares e agendamento com Fernanda Lemos, nutricionista em Passos, MG.', intro: 'Respostas para começar a conversa com mais tranquilidade.', updated: '2026-09-16', type: 'FAQPage' },
  { id: 'contato', path: 'contato/', label: 'Contato e localização', title: 'Contato e como chegar em Passos | Fernanda Lemos', heading: 'Vamos conversar<br>sobre <em>você?</em>', eyebrow: 'Contato e localização', description: 'Agende com Fernanda Lemos pelo WhatsApp (35) 99981-9701. Veja e-mail, Instagram, endereço em Passos, MG e mapa com orientações de como chegar.', intro: 'Os canais para o primeiro contato e as informações para o seu encontro.', updated: '2026-09-16', type: 'ContactPage', cta: false },
  { id: 'primeira-consulta', path: 'conteudos/primeira-consulta/', parent: 'conteudos', label: 'Sua primeira consulta', title: 'Como se preparar para a primeira consulta | Fernanda Lemos', heading: 'Sua primeira consulta,<br><em>com mais tranquilidade.</em>', eyebrow: 'Guia para o primeiro encontro', description: 'Veja o que vale anotar e quais informações confirmar com Fernanda Lemos antes da primeira consulta nutricional: dúvidas, rotina, local e agendamento.', intro: 'Uma preparação simples para lembrar do que importa na hora de conversar.', updated: '2026-09-16', cta: false },
  { id: 'privacidade', path: 'privacidade.html', label: 'Privacidade', title: 'Privacidade e funcionamento do site | Fernanda Lemos', heading: 'Cuidado também é<br><em>transparência.</em>', eyebrow: 'Privacidade', description: 'Entenda o funcionamento dos links de contato, da seleção de assuntos e do mapa incorporado no site de Fernanda Lemos.', intro: 'Informações claras sobre a navegação e os serviços externos.', updated: '2026-09-16', index: false, cta: false },
  { id: '404', path: '404.html', label: 'Página não encontrada', title: 'Página não encontrada | Fernanda Lemos', description: 'Encontre o início, os conteúdos e os canais de contato de Fernanda Lemos.', index: false, cta: false },
];
